// 功能模塊分類(項管)。順序與分組依實機後端選單 /get_role_menu(2026-10-05 查驗);
// prefixes 依路由前綴歸屬;nav 為選單 i18n 鍵。不在選單內的路由歸到最接近的模塊,並在 01 標註「不在選單」
module.exports = [
  { id: "M01", name: "首頁與帳號", en: "Home / Account", nav: "navigation.menu.home", prefixes: ["/", "/profile", "/second-page"],
    purpose: "後台登入後的首頁,以及管理員修改自己的密碼(右上角個人選單進入)。" },
  { id: "M02", name: "玩家管理", en: "Player Management", nav: "navigation.menu.playerManagement", prefixes: ["/players", "/player-profile-update-requests"],
    purpose: "查詢玩家清單與詳情(含各錢包餘額、轉回主錢包),停用/啟用玩家,審核玩家提出的個人資料修改申請。" },
  { id: "M03", name: "通知", en: "Notifications", nav: "navigation.menu.notifications", prefixes: ["/notifications"],
    purpose: "建立發送給全部或指定玩家的站內通知(可設定頻率、期間、是否彈窗),並查看通知對象名單。" },
  { id: "M04", name: "促銷活動", en: "Promotions", nav: "navigation.menu.promotions", prefixes: ["/promotions"],
    purpose: "設定存款類促銷活動(期間、適用等級、存款條件、派彩方式與頻率、流水要求),查看玩家報名(Opt-In)名單與派彩紀錄。" },
  { id: "M05", name: "錢包管理", en: "Wallets Management", nav: "navigation.menu.wallets", prefixes: ["/wallets/adjustment", "/wallets/refund", "/reports/deposit", "/reports/withdrawal"],
    purpose: "處理玩家錢包的人工調帳(Wallet Adjustment)與沖正(Credit Reversal),以及查詢存款、提款交易紀錄。屬於資金異動模塊,操作會直接影響玩家餘額。" },
  { id: "M06", name: "內容中心", en: "Contents Hub", nav: "navigation.menu.contentsHub", prefixes: ["/banners", "/announcements", "/terms-and-conditions", "/responsible-gaming/", "/status-declaration"],
    purpose: "管理前台顯示內容:Banner 廣告、公告、條款與細則、責任博彩說明、狀態聲明(多語系內容)。" },
  { id: "M07", name: "遊戲中心", en: "Games Hub", nav: "navigation.menu.gamesHub", prefixes: ["/games", "/game-category", "/game-provider", "/game-type", "/game-offering", "/featured-games", "/quickAccess"],
    purpose: "管理遊戲大廳:快捷入口、遊戲、精選遊戲、遊戲分類、遊戲供應商、遊戲產品線(Game Offering)、遊戲類型。" },
  { id: "M08", name: "支付通道", en: "PSP Hub", nav: "navigation.menu.pspHub", prefixes: ["/psp"],
    purpose: "管理支付服務商(PSP)通道:是否支援存款/提款、手續費、單筆上下限、圖示。" },
  { id: "M09", name: "維護排程", en: "Maintenance", nav: "navigation.menu.maintenance", prefixes: ["/maintenance"],
    purpose: "建立系統或遊戲供應商的維護排程(類型、對象、起訖時間、原因),並更新維護狀態。" },
  { id: "M10", name: "合規", en: "Compliance", nav: "navigation.menu.compliance", prefixes: ["/audits"],
    purpose: "後台操作稽核紀錄(誰在什麼時間、從哪個 IP 做了什麼操作)。" },
  { id: "M11", name: "系統設定", en: "Settings", nav: "navigation.menu.settings", prefixes: ["/users", "/roles"],
    purpose: "管理後台使用者帳號與角色權限(選單權限勾選),決定每個使用者看得到哪些模塊、能做哪些操作。" },
  { id: "M12", name: "報表", en: "Reports", nav: "navigation.menu.reports", prefixes: ["/reports/cashless-liability", "/reports/fund-transaction", "/reports/game-report", "/reports/revenue", "/reports/player-account-transaction", "/reports/download-center"],
    purpose: "財務與營運報表:無現金負債、資金交易、遊戲投注紀錄、營收、玩家帳戶交易(含舊版無現金負債與舊版營收),以及非同步匯出的下載中心。" },
  { id: "M13", name: "推薦獎勵", en: "Referral", nav: "navigation.menu.referral", prefixes: ["/referral-setting", "/reports/referral-report"],
    purpose: "設定推薦活動規則(期間、派彩頻率與方式、獎金池與上限、流水門檻),並查詢推薦報表。" },
  { id: "M14", name: "OkadaPlay", en: "OkadaPlay", nav: "navigation.menu.okadaPlay", prefixes: ["/okadaplay"],
    purpose: "以內嵌頁面(iframe)開啟 OkadaPlay(playcard.zone)管理後台。" },
  { id: "M15", name: "獎金(免費旋轉)", en: "Bonus / Free Spin", nav: "navigation.menu.bonus", prefixes: ["/bonus"],
    purpose: "向指定玩家或玩家等級發放遊戲供應商的免費旋轉(Playtech、Pragmatic Play、Omniplay),查詢發放紀錄、移除未使用的免費旋轉,以及查看使用報表。" },
  { id: "M16", name: "責任博彩報表", en: "Responsible Gaming", nav: "navigation.submenu.responsibleGaming", prefixes: ["/responsible-gaming-report", "/reports/self-exclusion", "/reports/betting-limit"],
    purpose: "責任博彩相關報表:投注限額變更與高使用率名單、自我排除名單(可切換狀態)。" },
  { id: "M00", name: "登入與錯誤頁", en: "Auth / System", nav: null, prefixes: ["/login", "/login-pagcor", "/not-authorized"],
    purpose: "後台登入(一般登入、PAGCOR 登入)與無權限提示頁。" },
];
