// 開發角色依測試退回清單,人工閱讀程式與對照實機截圖後補全的欄位資訊(2026-10-05)
// 欄位層級:match 比對欄位 label/placeholder/參數/元件名(包含即可或正則);
//   key 送出參數;label 更正後名稱(以實機畫面為準);note 補充說明;
//   cond 顯示條件(預設畫面看不到,實機比對時不算缺漏);liveMatch 實機畫面上用來比對的文字
// 頁面層級(page: true):ignoreExtra 畫面上非欄位的標題文字;note 頁面說明;tabHeaders 表頭在非預設頁籤
module.exports = [
  // ---- 實機查驗後補充:顯示條件 ----
  { path: "/announcements/add", match: "Media Type", cond: "開啟 Enable Popup 後顯示" },
  { path: "/announcements/add", match: "Video Link", cond: "開啟 Enable Popup 且 Media Type 選 Video 後顯示" },
  { path: "/announcements/update/:id()", match: "Banner Image", key: "banner", cond: "開啟 Enable Popup 且 Media Type 選 Image 時顯示", note: "未保留原圖時送 remove_banner=1" },
  { path: "/banners/add", match: "Video Link (Large)", cond: "Media Type 選 Video 後顯示" },
  { path: "/banners/add", match: "Video Link (Medium)", cond: "Media Type 選 Video 後顯示" },
  { path: "/banners/add", match: "Video Link (Small)", cond: "Media Type 選 Video 後顯示" },
  { path: "/banners/add", page: true, ignoreExtra: ["Large Banner", "Medium Banner", "Small Banner"], note: "圖片上傳分 Large / Medium / Small Banner 三區,各對應 Desktop(1368x360)、Tablet(768x360)、Mobile(500x500)" },
  { path: "/banners/update/:id()", match: /Desktop|Tablet|Mobile/, cond: "Media Type 為 Image 時顯示" },
  { path: "/banners/update/:id()", match: "Video Link", cond: "Media Type 為 Video 時顯示" },
  { path: "/bonus/playtech/freespin/reports", match: "Member ID", cond: "切換到 Game Records / Bonus Transaction 頁籤後顯示" },
  { path: "/bonus/pragmatic-play/freespin/reports", match: "Member ID", cond: "切換到 Game Records / Bonus Transaction 頁籤後顯示" },
  { path: "/bonus/omniplay/freespin/reports", match: "Member ID", cond: "切換到 Game Records / Bonus Transaction 頁籤後顯示" },
  { path: "/bonus/playtech/freespin/reports", match: "DateRangePicker", label: "Start Date ~ End Date" },
  { path: "/bonus/pragmatic-play/freespin/reports", match: "DateRangePicker", label: "Start Date ~ End Date" },
  { path: "/bonus/omniplay/freespin/reports", match: "DateRangePicker", label: "Start Date ~ End Date" },
  { path: "/featured-games/list", match: "Select Games", key: "game_ids", cond: "按「Add Featured eGames」後的對話框內" },
  { path: "/player-profile-update-requests/list", match: "Admin Password", cond: "核准/駁回確認對話框內,需輸入管理員密碼" },
  { path: "/player-profile-update-requests/list", match: "Rejection Reason", cond: "駁回對話框內" },
  { path: "/player-profile-update-requests/view/:id()", match: "Admin Password", cond: "核准/駁回確認對話框內,需輸入管理員密碼" },
  { path: "/player-profile-update-requests/view/:id()", match: "Rejection Reason", cond: "駁回對話框內" },
  { path: "/promotions/settings/view/:id()", match: /^Email$/, cond: "按 Activate / Deactivate 後的確認對話框內,需輸入管理員帳密" },
  { path: "/promotions/settings/view/:id()", match: /^Password$/, cond: "按 Activate / Deactivate 後的確認對話框內,需輸入管理員帳密" },
  { path: "/referral-setting/add", match: "Max Cap Amount", key: "max_cap_amount", cond: "Payout Type 選 percentage_by_deposit 時顯示", note: "選填,轉成數字送出" },
  { path: "/reports/betting-limit/list", match: "Limit Period", cond: "Limit Change Report 頁籤" },
  { path: "/responsible-gaming-report/betting-limit/list", match: "Limit Period", cond: "Limit Change Report 頁籤" },
  { path: "/reports/game-report/list", match: "Settlement", cond: "Date Filter Type 選 Settlement 時顯示(預設為 Transaction)" },
  { path: "/notifications/update/:id()", match: "Player ID", cond: "未勾選全部玩家(notification_all_patron)時顯示" },
  { path: "/notifications/add", match: "Player ID", cond: "未勾選全部玩家(notification_all_patron)時顯示" },
  { path: "/reports/self-exclusion/list", match: "VSwitch", label: "狀態切換(列表每列)", key: "—(列表列內操作)", cond: "列表每一列的狀態開關" },
  { path: "/responsible-gaming-report/self-exclusion/list", match: "VSwitch", label: "狀態切換(列表每列)", key: "—(列表列內操作)", cond: "列表每一列的狀態開關" },
  { path: "/announcements/add", match: "Banner Image", key: "banner", cond: "開啟 Enable Popup 且 Media Type 選 Image 時顯示", note: "Media Type 為 Video 時不送出,改送 video_link" },
  { path: "/reports/self-exclusion/list", page: true, headersFromLive: true, note: "表頭部分寫在頁面內,以實機為準" },
  { path: "/responsible-gaming-report/self-exclusion/list", page: true, headersFromLive: true, note: "表頭部分寫在頁面內,以實機為準" },
  { path: "/responsible-gaming/list", page: true, ignoreExtra: ["Title", "Content", "Status"], note: "每個語系一張卡片,顯示 Title、Content、Updated At / By,按 Edit 進入該語系編輯" },
  { path: "/terms-and-conditions/list", page: true, ignoreExtra: ["Title", "Content", "Status"], note: "每個語系一張卡片,顯示 Title、Content、Updated At / By,按 Edit 進入該語系編輯" },
  { path: "/status-declaration/list", page: true, ignoreExtra: ["Title", "Content", "Status"], note: "卡片顯示 Status、Content、Updated At / By,按 Edit 進入編輯" },
  // ---- 實機查驗後補充:名稱以實機畫面為準 ----
  { path: "/promotions/settings/add", match: "TiptapEditor", label: "Terms and Conditions", key: "term_and_condition", note: "富文本編輯器" },
  { path: "/referral-setting/update/:id()", match: /terms and conditions/i, label: "Terms and Conditions", liveMatch: "Terms and Conditions" },
  { path: "/game-type/update/:id()", match: "Enter Game Type Name", label: "Game Type Name", key: "game_type_name" },
  { path: "/game-type/update/:id()", page: true, ignoreExtra: ["Game Type Code"], note: "Game Type Code 只顯示不可改" },
  { path: "/games/add", match: /^RTP$/, label: "RTP (%)" },
  { path: "/games/update/:id()", match: /^RTP$/, label: "RTP (%)" },
  { path: "/games/add", match: "file", label: "Game Image", key: "game_image" },
  { path: "/games/update/:id()", match: "file", label: "Game Image", key: "game_image" },
  { path: "/promotions/settings/add", match: /^Percentage$/, label: "Percentage(%)" },
  { path: "/promotions/settings/add", match: "Upload Banner", label: "Banner", liveMatch: "Banner", key: "banner_image" },
  { path: "/psp/update/:id()", match: "Supported formats", label: "Icon", key: "icon", cond: "圖示上傳區(標籤在圖片預覽旁)", note: "PNG、JPG、SVG、WebP,≤ 5MB;有選新圖才送出(改用 FormData + _method=PUT)" },
  { path: "/psp/update/:id()", page: true, ignoreExtra: ["Code", "External Code", "Type", "Category"], note: "編輯頁 Code、External Code、Type、Category 只顯示不可改" },
  { path: "/maintenance/update/:id()", page: true, ignoreExtra: ["Type", "Target", "Schedule Start DateTime", "Schedule End DateTime"], note: "編輯頁只能改 Reason 與 Status;Type、Target、排程時間只顯示" },
  { path: "/referral-setting/update/:id()", page: true, ignoreExtra: ["Payout Amount"] },
  { path: "/notifications/add", page: true, ignoreExtra: ["Content (Recommended total image size not more than 4mb for optimal performance)"] },
  { path: "/notifications/update/:id()", page: true, ignoreExtra: ["Content (Recommended total image size not more than 4mb for optimal performance)"] },
  { path: "/roles/add", page: true, ignoreExtra: ["Search permissions"], note: "權限勾選區上方有搜尋框可篩選選單" },
  { path: "/roles/update/:id()", page: true, ignoreExtra: ["Search permissions"] },
  { path: "/profile", page: true, ignoreExtra: ["Name", "Email", "Role"], note: "上方顯示自己的 Name、Email、Role(唯讀),下方修改密碼" },
  { path: "/players/view/:id()", page: true, tabHeaders: true, note: "分 Player Details、Wallet Details 兩個頁籤;錢包表格在 Wallet Details 頁籤" },
  { path: "/game-category/add", match: "Max size: 5MB", label: "Game Category Image", key: "game_category_image", note: "選填;JPEG、PNG、JPG、GIF、WEBP、SVG,≤ 5MB" },
  { path: "/game-category/update/:id()", match: "Max size: 5MB", label: "Game Category Image", key: "game_category_image", note: "選填,有選新圖才送出" },
  { path: "/game-type/update/:id()", match: "Max size: 5MB", label: "Game Type Image", key: "game_type_image", note: "選填,有選新圖才送出" },
  { path: "/responsible-gaming/update/:id()", page: true, ignoreExtra: ["Language"], note: "依語系編輯,Language 只顯示" },
  { path: "/terms-and-conditions/update/:id()", page: true, ignoreExtra: ["Language"], note: "依語系編輯,Language 只顯示" },
  // ---- 第一輪(靜態)補全 ----
  { path: "/announcements/add", match: "Banner Image", key: "banner", note: "開啟彈窗且媒體類型為 video 時不送出,改送 video_link" },
  { path: "/announcements/add", match: "Start Date ~ End Date", key: "start_date ~ end_date" },
  { path: "/announcements/add", match: /^Status$/, key: "active_status" },
  { path: "/announcements/add", match: "Enable Popup", key: "is_enable_pop_up", note: "開啟後才顯示媒體類型、影片連結" },
  { path: "/announcements/add", match: "TiptapEditor", label: "Content", key: "announcement_content", note: "送出前以 Base64 編碼 HTML" },
  { path: "/announcements/update/:id()", match: "Start Date ~ End Date", key: "start_date ~ end_date" },
  { path: "/announcements/update/:id()", match: /^Status$/, key: "active_status" },
  { path: "/announcements/update/:id()", match: "Enable Popup", key: "is_enable_pop_up" },
  { path: "/announcements/update/:id()", match: "TiptapEditor", label: "Content", key: "announcement_content", note: "送出前以 Base64 編碼 HTML" },
  { path: "/game-type/update/:id()", match: "Max size: 5MB", label: "Game Type Image", key: "game_type_image", note: "選填,有選新圖才送出" },
  { path: "/maintenance/add", match: "Schedule Start DateTime", key: "schedule_start_dateTime ~ schedule_end_dateTime", note: "選填,有值才送出" },
  { path: "/notifications/add", match: "TiptapEditor", label: "Content", key: "notification_content", note: "送出前以 Base64 編碼 HTML" },
  { path: "/notifications/add", match: "Recommended total image size", label: "Content", key: "notification_content", note: "送出前以 Base64 編碼 HTML;建議內文圖片總大小 ≤ 4MB" },
  { path: "/notifications/update/:id()", match: "Recommended total image size", label: "Content", key: "notification_content", note: "送出前以 Base64 編碼 HTML;建議內文圖片總大小 ≤ 4MB" },
  { path: "/psp/add", match: /^Code$/, key: "—(不送出)", note: "唯讀,由 Name 自動產生:轉小寫、空白改底線" },
  { path: "/quickAccess/add", match: "VSwitch", label: "Status", key: "status", note: "開關顯示 Active / Inactive" },
  { path: "/quickAccess/add", match: "file", label: "Icon", key: "icon", note: "選填" },
  { path: "/quickAccess/update/:id()", match: "VSwitch", label: "Status", key: "status", note: "開關顯示 Active / Inactive" },
  { path: "/quickAccess/update/:id()", match: "file", label: "Icon", key: "icon", note: "選填" },
  { path: "/referral-setting/add", match: "total_max_payout_percent", label: "Payout Percentage / Payout Amount", key: "total_max_payout_percent", note: "標籤依 Payout Type 切換:percentage_by_deposit 顯示 %,fixed_amount 顯示金額" },
  { path: "/referral-setting/update/:id()", match: /^(Min Deposit Amount|Max Cap Amount|Min Turnover Amount|Pool Amount)$/, key: "—(不送出)", note: "只顯示;此頁送出內容只有 active_status" },
];
