// 開發角色依測試退回清單,人工閱讀送出程式後補全的欄位資訊(2026-10-05)
// match:比對欄位 label(包含即可)或元件名;key:送出參數;label:更正後名稱;note:補充說明
module.exports = [
  { path: "/announcements/add", match: "Banner Image", key: "banner", note: "開啟彈窗且媒體類型為 video 時不送出,改送 video_link" },
  { path: "/announcements/add", match: "Start Date ~ End Date", key: "start_date ~ end_date" },
  { path: "/announcements/add", match: /^Status$/, key: "active_status" },
  { path: "/announcements/add", match: "Enable Popup", key: "is_enable_pop_up", note: "開啟後才顯示媒體類型、影片連結" },
  { path: "/announcements/add", match: "TiptapEditor", label: "Content", key: "announcement_content", note: "送出前以 Base64 編碼 HTML" },
  { path: "/announcements/update/:id()", match: "Banner Image", key: "banner", note: "未保留原圖時送 remove_banner=1" },
  { path: "/announcements/update/:id()", match: "Start Date ~ End Date", key: "start_date ~ end_date" },
  { path: "/announcements/update/:id()", match: /^Status$/, key: "active_status" },
  { path: "/announcements/update/:id()", match: "Enable Popup", key: "is_enable_pop_up" },
  { path: "/announcements/update/:id()", match: "TiptapEditor", label: "Content", key: "announcement_content", note: "送出前以 Base64 編碼 HTML" },
  { path: "/game-category/add", match: "Max size: 5MB", label: "Category Image", key: "game_category_image", note: "選填" },
  { path: "/game-category/update/:id()", match: "Max size: 5MB", label: "Category Image", key: "game_category_image", note: "選填,有選新圖才送出" },
  { path: "/game-type/update/:id()", match: "Max size: 5MB", label: "Game Type Image", key: "game_type_image", note: "選填,有選新圖才送出" },
  { path: "/maintenance/add", match: "Schedule Start DateTime", key: "schedule_start_dateTime ~ schedule_end_dateTime", note: "選填,有值才送出" },
  { path: "/notifications/add", match: "TiptapEditor", label: "Content", key: "notification_content", note: "送出前以 Base64 編碼 HTML" },
  { path: "/notifications/add", match: "Recommended total image size", label: "Content", key: "notification_content", note: "送出前以 Base64 編碼 HTML;建議內文圖片總大小 ≤ 4MB" },
  { path: "/notifications/update/:id()", match: "Recommended total image size", label: "Content", key: "notification_content", note: "送出前以 Base64 編碼 HTML;建議內文圖片總大小 ≤ 4MB" },
  { path: "/psp/add", match: /^Code$/, key: "—(不送出)", note: "唯讀,由 Name 自動產生:轉小寫、空白改底線" },
  { path: "/quickAccess/add", match: "VSwitch", label: "Status", key: "status", note: "開關顯示 Active / Inactive" },
  { path: "/quickAccess/add", match: "file", label: "Icon", key: "icon", note: "選填" },
  { path: "/quickAccess/update/:id()", match: "VSwitch", label: "Status", key: "status", note: "開關顯示 Active / Inactive" },
  { path: "/quickAccess/update/:id()", match: "file", label: "Icon", key: "icon", note: "選填" },
  { path: "/referral-setting/add", match: "total_max_payout_percent", label: "Payout Percentage / Payout Amount", key: "total_max_payout_percent", note: "標籤依 Payout Type 切換:percentage_by_deposit 顯示 %,fixed_amount 顯示金額" },
  { path: "/referral-setting/add", match: "Max Cap Amount", key: "max_cap_amount", note: "選填,轉成數字送出" },
  { path: "/referral-setting/update/:id()", match: /^(Min Deposit Amount|Max Cap Amount|Min Turnover Amount|Pool Amount)$/, key: "—(不送出)", note: "只顯示;此頁送出內容只有 active_status" },
];
